# Generated by Django 4.2 on 2024-06-19 11:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cp_name', models.CharField(max_length=255)),
                ('cp_customer_vendor', models.CharField(max_length=255)),
                ('cp_start_date', models.DateField(null=True)),
                ('cp_end_date', models.DateField(null=True)),
                ('cp_tig_entity', models.CharField(blank=True, max_length=255)),
                ('cp_region', models.CharField(choices=[('APAC', 'APAC'), ('EMEA', 'EMEA'), ('MEA', 'MEA'), ('NA', 'NA'), ('LATAM', 'LATAM'), ('AMEA', 'AMEA'), ('ANZ', 'ANZ')], max_length=5)),
                ('cp_status', models.CharField(choices=[('Transition', 'Transition'), ('BAU', 'BAU'), ('Descoped', 'Descoped')], max_length=16)),
                ('cp_end_customer', models.CharField(blank=True, max_length=255)),
                ('cp_type', models.CharField(choices=[('Workspace infrastructure', 'Workspace infrastructure'), ('Enterprise Infrastructure', 'Enterprise Infrastructure')], max_length=32)),
                ('cp_payment_terms', models.CharField(choices=[('NET0', 'NET0'), ('NET10', 'NET10'), ('NET30', 'NET30'), ('NET45', 'NET45'), ('NET60', 'NET60'), ('NET90', 'NET90')], max_length=8)),
                ('cp_cancelled_ticket_billable', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=4)),
                ('cp_billing_frequency', models.CharField(choices=[('One Time', 'One Time'), ('Weekly', 'Weekly'), ('Bi-Weekly', 'Bi-Weekly'), ('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Half-Yearly', 'Half-Yearly'), ('Yearly', 'Yearly'), ('ADHOC', 'ADHOC')], max_length=16)),
                ('cp_cancellation_window_1', models.CharField(blank=True, max_length=255)),
                ('cp_cancellation_window_2', models.CharField(blank=True, max_length=255)),
                ('cp_cancelled_ticket_mutiplier_1', models.CharField(blank=True, max_length=255)),
                ('cp_terms_and_conditions', models.TextField(blank=True, max_length=255)),
                ('cp_owner', models.CharField(blank=True, max_length=255)),
                ('cp_last_billing_date', models.DateField(null=True)),
                ('cp_record_type', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
