# Generated by Django 4.2 on 2024-06-19 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerproject',
            name='cp_tig_entity',
            field=models.CharField(choices=[('Total IT Consult LLP', 'Total IT Consult LLP'), ('Total IT Consult Pty ltd', 'Total IT Consult Pty ltd'), ('Total IT Global Pte Ltd', 'Total IT Global Pte Ltd'), ('Total IT Global Sdn. Bhd.', 'Total IT Global Sdn. Bhd.'), ('Total IT Global KK,Japan', 'Total IT Global KK,Japan'), ('TIC Netherlands B.V.', 'TIC Netherlands B.V.'), ('Total IT Global Inc.', 'Total IT Global Inc.'), ('Total IT Global NZ Ltd', 'Total IT Global NZ Ltd'), ('Total IT Global HK Ltd', 'Total IT Global HK Ltd'), ('Total IT Consult DK ApS', 'Total IT Consult DK ApS'), ('Total IT Global Finalnd OY', 'Total IT Global Finalnd OY'), ('TOTAL IT GLOBAL POLAND Sp. z o .o', 'TOTAL IT GLOBAL POLAND Sp. z o .o'), ('Total IT Global France', 'Total IT Global France'), ('Total IT Global Company Limited', 'Total IT Global Company Limited'), ('Total IT Global Germany GMBH', 'Total IT Global Germany GMBH'), ('Total IT Norway AS', 'Total IT Norway AS'), ('TI Global Sweden AB', 'TI Global Sweden AB'), ('Total IT Global UK Limited', 'Total IT Global UK Limited')], max_length=64),
        ),
    ]
