# Generated by Django 4.2 on 2024-06-19 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_customerproject_cp_tig_entity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerproject',
            name='cp_cancelled_ticket_billable',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=4),
        ),
        migrations.AlterField(
            model_name='customerproject',
            name='cp_end_customer',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='customerproject',
            name='cp_end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='customerproject',
            name='cp_region',
            field=models.CharField(blank=True, choices=[('APAC', 'APAC'), ('EMEA', 'EMEA'), ('MEA', 'MEA'), ('NA', 'NA'), ('LATAM', 'LATAM'), ('AMEA', 'AMEA'), ('ANZ', 'ANZ')], max_length=5),
        ),
        migrations.AlterField(
            model_name='customerproject',
            name='cp_start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='customerproject',
            name='cp_type',
            field=models.CharField(blank=True, choices=[('Workspace infrastructure', 'Workspace infrastructure'), ('Enterprise Infrastructure', 'Enterprise Infrastructure')], max_length=32),
        ),
    ]
