# Generated by Django 4.2 on 2024-06-19 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_customerproject_cp_cancelled_ticket_billable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerproject',
            name='cp_last_billing_date',
            field=models.DateField(blank=True),
        ),
    ]
