# Generated by Django 4.2 on 2024-06-19 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_customerproject_cp_last_billing_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerproject',
            name='cp_status',
            field=models.CharField(blank=True, choices=[('Transition', 'Transition'), ('BAU', 'BAU'), ('Descoped', 'Descoped')], max_length=16),
        ),
    ]
