# Generated by Django 4.2 on 2024-06-20 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_customeraccount_created_by_and_more'),
        ('projects', '0005_alter_customerproject_cp_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerproject',
            name='cp_customer_vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cp_customer_vendor', to='accounts.customeraccount'),
        ),
        migrations.AlterField(
            model_name='customerproject',
            name='cp_end_customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cp_end_customer', to='accounts.customeraccount'),
        ),
    ]
