# Generated by Django 4.2 on 2024-06-20 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_customerproject_cp_customer_vendor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerproject',
            name='cp_last_billing_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
