# Generated by Django 4.2 on 2024-07-12 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_remove_customerproject_cp_record_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerproject',
            name='record_type',
            field=models.CharField(max_length=255),
        ),
    ]
