# Generated by Django 4.2 on 2024-07-12 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_alter_customerproject_record_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerproject',
            name='cp_status',
            field=models.CharField(choices=[('Transition', 'Transition'), ('BAU', 'BAU'), ('Descoped', 'Descoped')], max_length=16),
        ),
    ]
