# Generated by Django 4.2 on 2024-07-16 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_alter_customerproject_cp_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorproject',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorproject',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='vendorproject',
            name='vp_billing_frequency',
            field=models.CharField(blank=True, choices=[('One Time', 'One Time'), ('Weekly', 'Weekly'), ('Bi Weekly', 'Bi Weekly'), ('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Half Year', 'Half Year'), ('Yearly', 'Yearly'), ('Adhoc', 'Adhoc')], max_length=64),
        ),
        migrations.AlterField(
            model_name='vendorproject',
            name='vp_region',
            field=models.CharField(blank=True, choices=[('APAC', 'APAC'), ('EMEA', 'EMEA'), ('MEA', 'MEA'), ('NA', 'NA'), ('LATAM', 'LATAM'), ('AMEA', 'AMEA'), ('ANZ', 'ANZ')], max_length=64),
        ),
        migrations.AlterField(
            model_name='vendorproject',
            name='vp_status',
            field=models.CharField(blank=True, choices=[('Transition', 'Transition'), ('BAU', 'BAU'), ('Hold', 'Hold'), ('Terminated', 'Terminated')], max_length=64),
        ),
        migrations.AlterField(
            model_name='vendorproject',
            name='vp_type_of_project',
            field=models.CharField(blank=True, choices=[('Workspace Infrastructure', 'Workspace Infrastructure'), ('Enterprise Infrastructure', 'Enterprise Infrastructure')], max_length=64),
        ),
    ]
