# Generated by Django 4.2 on 2024-07-12 08:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FteSerivce',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fte_serivce_name', models.CharField(max_length=255)),
                ('fte_serivce_project', models.CharField(max_length=255)),
                ('fte_serivce_project_resource_roaster', models.CharField(max_length=255)),
                ('fte_serivce_project_site', models.CharField(max_length=255)),
                ('fte_serivce_customer_purchase_order', models.CharField(max_length=255)),
                ('fte_serivce_service_type', models.CharField(choices=[('FTE', 'FTE')], max_length=255)),
                ('fte_serivce_sourced_by', models.CharField(choices=[('TotalIT', 'TotalIT'), ('Vendor', 'Vendor')], max_length=255)),
                ('fte_serivce_subtype_type', models.CharField(choices=[('FTE Overtime Hourly', 'FTE Overtime Hourly'), ('FTE Overtime Half Day', 'FTE Overtime Half Day'), ('FTE Overtime Full Day', 'FTE Overtime Full Day'), ('Backfill Half Day - First Half', 'Backfill Half Day - First Half'), ('Backfill Half Day - Second Half', 'Backfill Half Day - Second Half'), ('Backfill Full Day ', 'Backfill Full Day '), ('Backfill Overtime Hourly', 'Backfill Overtime Hourly'), ('Backfill Overtime Half Day', 'Backfill Overtime Half Day'), ('Backfill Overtime Full Day', 'Backfill Overtime Full Day')], max_length=255)),
                ('fte_serivce_start_date', models.CharField(max_length=255)),
                ('fte_serivce_end_date', models.CharField(max_length=255)),
                ('fte_serivce_category', models.CharField(choices=[('EUC(End User Computing)', 'EUC(End User Computing)'), ('Network', 'Network'), ('Server', 'Server'), ('Storage', 'Storage')], max_length=255)),
                ('fte_serivce_skill_level', models.CharField(choices=[('L0', 'L0'), ('L0.5', 'L0.5'), ('L1', 'L1'), ('L1.5', 'L1.5'), ('L2', 'L2'), ('L3', 'L3')], max_length=255)),
                ('fte_serivce_description', models.TextField(blank=True, max_length=1024)),
                ('fte_serivce_customer_currency', models.CharField(choices=[('AED - UAE Dirham', 'AED - UAE Dirham'), ('AUD - Australian Dollar', 'AUD - Australian Dollar'), ('CAD - Canadian Dollar', 'CAD - Canadian Dollar'), ('CHF - Swiss Franc', 'CHF - Swiss Franc'), ('DKK - Danish Krone', 'DKK - Danish Krone'), ('EUR - Euro', 'EUR - Euro'), ('GBP - British Pound', 'GBP - British Pound'), ('HKD - Hong Kong Dollar', 'HKD - Hong Kong Dollar'), ('INR - Indian Rupee', 'INR - Indian Rupee'), ('JPY - Japanese Yen', 'JPY - Japanese Yen'), ('KRW - Korean Won', 'KRW - Korean Won'), ('MYR - Malaysian Ringgit', 'MYR - Malaysian Ringgit'), ('NOK - Norwegian Krone', 'NOK - Norwegian Krone'), ('NZD - New Zealand Dollar', 'NZD - New Zealand Dollar'), ('PLN - Polish Zloty', 'PLN - Polish Zloty'), ('SEK - Swedish Krona', 'SEK - Swedish Krona'), ('SGD - Singapore Dollar', 'SGD - Singapore Dollar'), ('THB - Thai Baht', 'THB - Thai Baht'), ('USD - U.S. Dollar', 'USD - U.S. Dollar')], max_length=255)),
                ('fte_serivce_customer_standby_fees', models.CharField(max_length=255)),
                ('fte_serivce_customer_day_rate', models.CharField(max_length=255)),
                ('fte_serivce_customer_additional_hrs_rate_oh', models.CharField(max_length=255)),
                ('fte_serivce_customer_monthly_rate', models.CharField(max_length=255)),
                ('fte_serivce_customer_additional_hrs_rate_ooh', models.CharField(max_length=255)),
                ('fte_serivce_customer_weekend_hourly', models.CharField(max_length=255)),
                ('fte_serivce_customer_half_day', models.CharField(blank=True, max_length=255)),
                ('fte_serivce_customer_weekend_half_day', models.CharField(blank=True, max_length=255)),
                ('fte_serivce_customer_ot_rate', models.CharField(blank=True, max_length=255)),
                ('fte_serivce_customer_weekend_full_day', models.CharField(blank=True, max_length=255)),
                ('fte_serivce_customer_ph_hourly', models.CharField(max_length=255)),
                ('fte_serivce_customer_tm_rate_hrs', models.CharField(max_length=255)),
                ('fte_serivce_customer_ph_half_day', models.CharField(max_length=255)),
                ('fte_serivce_customer_ph_full_day', models.CharField(max_length=255)),
                ('fte_serivce_customer_quote_po_conversion_rate', models.CharField(max_length=255)),
                ('fte_serivce_vendor_name', models.CharField(max_length=255)),
                ('fte_serivce_vendor_project', models.CharField(max_length=255)),
                ('fte_serivce_purchase_order', models.CharField(max_length=255)),
                ('fte_serivce_vendor_currency', models.CharField(choices=[('AED - UAE Dirham', 'AED - UAE Dirham'), ('AUD - Australian Dollar', 'AUD - Australian Dollar'), ('CAD - Canadian Dollar', 'CAD - Canadian Dollar'), ('CHF - Swiss Franc', 'CHF - Swiss Franc'), ('DKK - Danish Krone', 'DKK - Danish Krone'), ('EUR - Euro', 'EUR - Euro'), ('GBP - British Pound', 'GBP - British Pound'), ('HKD - Hong Kong Dollar', 'HKD - Hong Kong Dollar'), ('INR - Indian Rupee', 'INR - Indian Rupee'), ('JPY - Japanese Yen', 'JPY - Japanese Yen'), ('KRW - Korean Won', 'KRW - Korean Won'), ('MYR - Malaysian Ringgit', 'MYR - Malaysian Ringgit'), ('NOK - Norwegian Krone', 'NOK - Norwegian Krone'), ('NZD - New Zealand Dollar', 'NZD - New Zealand Dollar'), ('PLN - Polish Zloty', 'PLN - Polish Zloty'), ('SEK - Swedish Krona', 'SEK - Swedish Krona'), ('SGD - Singapore Dollar', 'SGD - Singapore Dollar'), ('THB - Thai Baht', 'THB - Thai Baht'), ('USD - U.S. Dollar', 'USD - U.S. Dollar')], max_length=255)),
                ('fte_serivce_vendor_standby_fees', models.CharField(max_length=255)),
                ('fte_serivce_vendor_day_rate', models.CharField(max_length=255)),
                ('fte_serivce_vendor_additional_hrs_rate_oh', models.CharField(max_length=255)),
                ('fte_serivce_vendor_monthly_rate', models.CharField(max_length=255)),
                ('fte_serivce_vendor_additional_hrs_rate_ooh', models.CharField(max_length=255)),
                ('fte_serivce_vendor_weekend_hourly', models.CharField(max_length=255)),
                ('fte_serivce_vendor_half_day', models.CharField(blank=True, max_length=255)),
                ('fte_serivce_vendor_weekend_half_day', models.CharField(blank=True, max_length=255)),
                ('fte_serivce_vendor_ot_rate', models.CharField(blank=True, max_length=255)),
                ('fte_serivce_vendor_weekend_full_day', models.CharField(blank=True, max_length=255)),
                ('fte_serivce_vendor_ph_hourly', models.CharField(max_length=255)),
                ('fte_serivce_vendor_tm_rate_hrs', models.CharField(max_length=255)),
                ('fte_serivce_vendor_ph_half_day', models.CharField(max_length=255)),
                ('fte_serivce_vendor_ph_full_day', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
