# Generated by Django 4.2 on 2024-07-16 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_vendorproject_created_at_vendorproject_updated_at_and_more'),
        ('accounts', '0012_remove_vendoraccount_va_spoc_name_and_more'),
        ('orders', '0008_alter_salesorder_so_po_amount_utilised_and_more'),
        ('project_site', '0004_alter_projectsite_ps_working_days'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fteserivce',
            name='fte_serivce_customer_additional_hrs_rate_oh',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='fteserivce',
            name='fte_serivce_customer_additional_hrs_rate_ooh',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='fteserivce',
            name='fte_serivce_customer_day_rate',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='fteserivce',
            name='fte_serivce_customer_half_day',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='fteserivce',
            name='fte_serivce_customer_monthly_rate',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='fteserivce',
            name='fte_serivce_customer_ot_rate',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='fteserivce',
            name='fte_serivce_customer_ph_full_day',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='fteserivce',
            name='fte_serivce_customer_ph_half_day',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='fteserivce',
            name='fte_serivce_customer_ph_hourly',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='fteserivce',
            name='fte_serivce_customer_purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fte_serivce_customer_purchase_order_fk', to='orders.salesorder'),
        ),
        migrations.AlterField(
            model_name='fteserivce',
            name='fte_serivce_customer_standby_fees',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='fteserivce',
            name='fte_serivce_customer_tm_rate_hrs',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='fteserivce',
            name='fte_serivce_customer_weekend_full_day',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='fteserivce',
            name='fte_serivce_customer_weekend_half_day',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='fteserivce',
            name='fte_serivce_customer_weekend_hourly',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='fteserivce',
            name='fte_serivce_end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='fteserivce',
            name='fte_serivce_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fte_serivce_project_fk', to='projects.customerproject'),
        ),
        migrations.AlterField(
            model_name='fteserivce',
            name='fte_serivce_project_site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fte_serivce_project_site_fk', to='project_site.projectsite'),
        ),
        migrations.AlterField(
            model_name='fteserivce',
            name='fte_serivce_start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='fteserivce',
            name='fte_serivce_vendor_additional_hrs_rate_oh',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='fteserivce',
            name='fte_serivce_vendor_additional_hrs_rate_ooh',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='fteserivce',
            name='fte_serivce_vendor_day_rate',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='fteserivce',
            name='fte_serivce_vendor_half_day',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='fteserivce',
            name='fte_serivce_vendor_monthly_rate',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='fteserivce',
            name='fte_serivce_vendor_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fte_serivce_vendor_name_fk', to='accounts.vendoraccount'),
        ),
        migrations.AlterField(
            model_name='fteserivce',
            name='fte_serivce_vendor_ot_rate',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='fteserivce',
            name='fte_serivce_vendor_ph_full_day',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='fteserivce',
            name='fte_serivce_vendor_ph_half_day',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='fteserivce',
            name='fte_serivce_vendor_ph_hourly',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='fteserivce',
            name='fte_serivce_vendor_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fte_serivce_vendor_project_fk', to='projects.vendorproject'),
        ),
        migrations.AlterField(
            model_name='fteserivce',
            name='fte_serivce_vendor_standby_fees',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='fteserivce',
            name='fte_serivce_vendor_tm_rate_hrs',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='fteserivce',
            name='fte_serivce_vendor_weekend_full_day',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='fteserivce',
            name='fte_serivce_vendor_weekend_half_day',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='fteserivce',
            name='fte_serivce_vendor_weekend_hourly',
            field=models.FloatField(),
        ),
    ]
