# Generated by Django 4.2 on 2024-07-16 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_fteserivce_fte_serivce_customer_additional_hrs_rate_oh_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fteserivce',
            name='fte_serivce_customer_additional_hrs_rate_oh',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='fteserivce',
            name='fte_serivce_customer_additional_hrs_rate_ooh',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='fteserivce',
            name='fte_serivce_customer_day_rate',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='fteserivce',
            name='fte_serivce_customer_half_day',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='fteserivce',
            name='fte_serivce_customer_ot_rate',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='fteserivce',
            name='fte_serivce_customer_ph_full_day',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='fteserivce',
            name='fte_serivce_customer_ph_half_day',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='fteserivce',
            name='fte_serivce_customer_ph_hourly',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='fteserivce',
            name='fte_serivce_customer_standby_fees',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='fteserivce',
            name='fte_serivce_customer_tm_rate_hrs',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='fteserivce',
            name='fte_serivce_customer_weekend_full_day',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='fteserivce',
            name='fte_serivce_customer_weekend_half_day',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='fteserivce',
            name='fte_serivce_customer_weekend_hourly',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='fteserivce',
            name='fte_serivce_vendor_additional_hrs_rate_oh',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='fteserivce',
            name='fte_serivce_vendor_additional_hrs_rate_ooh',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='fteserivce',
            name='fte_serivce_vendor_day_rate',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='fteserivce',
            name='fte_serivce_vendor_half_day',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='fteserivce',
            name='fte_serivce_vendor_monthly_rate',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='fteserivce',
            name='fte_serivce_vendor_ot_rate',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='fteserivce',
            name='fte_serivce_vendor_ph_full_day',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='fteserivce',
            name='fte_serivce_vendor_ph_half_day',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='fteserivce',
            name='fte_serivce_vendor_ph_hourly',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='fteserivce',
            name='fte_serivce_vendor_standby_fees',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='fteserivce',
            name='fte_serivce_vendor_tm_rate_hrs',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='fteserivce',
            name='fte_serivce_vendor_weekend_full_day',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='fteserivce',
            name='fte_serivce_vendor_weekend_half_day',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='fteserivce',
            name='fte_serivce_vendor_weekend_hourly',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
