# Generated by Django 4.2 on 2024-07-16 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_vendorproject_created_at_vendorproject_updated_at_and_more'),
        ('accounts', '0012_remove_vendoraccount_va_spoc_name_and_more'),
        ('services', '0004_alter_fteserivce_fte_serivce_customer_additional_hrs_rate_oh_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fteserivce',
            name='fte_serivce_vendor_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fte_serivce_vendor_name_fk', to='accounts.vendoraccount'),
        ),
        migrations.AlterField(
            model_name='fteserivce',
            name='fte_serivce_vendor_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fte_serivce_vendor_project_fk', to='projects.vendorproject'),
        ),
    ]
