# Generated by Django 4.2 on 2024-07-16 13:01

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_alter_fteserivce_fte_serivce_customer_quote_po_conversion_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fteserivce',
            name='fte_serivce_subtype_type',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('FTE Overtime Hourly', 'FTE Overtime Hourly'), ('FTE Overtime Half Day', 'FTE Overtime Half Day'), ('FTE Overtime Full Day', 'FTE Overtime Full Day'), ('Backfill Half Day - First Half', 'Backfill Half Day - First Half'), ('Backfill Half Day - Second Half', 'Backfill Half Day - Second Half'), ('Backfill Full Day ', 'Backfill Full Day'), ('Backfill Overtime Hourly', 'Backfill Overtime Hourly'), ('Backfill Overtime Half Day', 'Backfill Overtime Half Day'), ('Backfill Overtime Full Day', 'Backfill Overtime Full Day')], max_length=1024),
        ),
    ]
