# Generated by Django 4.2 on 2024-07-22 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_alter_fteserivce_fte_serivce_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fteserivce',
            name='fte_serivce_vendor_currency',
            field=models.CharField(blank=True, choices=[('AED - UAE Dirham', 'AED - UAE Dirham'), ('AUD - Australian Dollar', 'AUD - Australian Dollar'), ('CAD - Canadian Dollar', 'CAD - Canadian Dollar'), ('CHF - Swiss Franc', 'CHF - Swiss Franc'), ('DKK - Danish Krone', 'DKK - Danish Krone'), ('EUR - Euro', 'EUR - Euro'), ('GBP - British Pound', 'GBP - British Pound'), ('HKD - Hong Kong Dollar', 'HKD - Hong Kong Dollar'), ('INR - Indian Rupee', 'INR - Indian Rupee'), ('JPY - Japanese Yen', 'JPY - Japanese Yen'), ('KRW - Korean Won', 'KRW - Korean Won'), ('MYR - Malaysian Ringgit', 'MYR - Malaysian Ringgit'), ('NOK - Norwegian Krone', 'NOK - Norwegian Krone'), ('NZD - New Zealand Dollar', 'NZD - New Zealand Dollar'), ('PLN - Polish Zloty', 'PLN - Polish Zloty'), ('SEK - Swedish Krona', 'SEK - Swedish Krona'), ('SGD - Singapore Dollar', 'SGD - Singapore Dollar'), ('THB - Thai Baht', 'THB - Thai Baht'), ('USD - U.S. Dollar', 'USD - U.S. Dollar')], max_length=255, null=True),
        ),
    ]
