# Generated by Django 4.2 on 2024-07-24 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_alter_fteserivce_fte_serivce_vendor_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fteserivce',
            name='fte_serivce_vendor_monthly_rate',
            field=models.FloatField(default=None, null=True),
        ),
    ]
