# Generated by Django 4.2 on 2024-06-13 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_customeraccount_ca_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeraccount',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='customeraccount',
            name='updated_by',
        ),
    ]
