# Generated by Django 4.2 on 2024-07-05 11:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
        ('accounts', '0003_remove_customeraccount_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('va_name', models.CharField(max_length=255)),
                ('va_phone_no', models.CharField(blank=True, max_length=255)),
                ('va_parent_acc', models.CharField(blank=True, max_length=255)),
                ('va_record_type', models.CharField(blank=True, max_length=255)),
                ('va_company_group', models.CharField(blank=True, max_length=255)),
                ('va_phone_number', models.CharField(blank=True, max_length=11)),
                ('va_account_owner', models.CharField(blank=True, max_length=255)),
                ('va_status', models.CharField(blank=True, choices=[('Initiation', 'Initiation'), ('NDA', 'NDA'), ('VRF', 'VRF'), ('Due Dligence', 'Due Dligence'), ('MSA', 'MSA'), ('Registration', 'Registration'), ('Active', 'Active'), ('Rejected', 'Rejected'), ('Blacklisted', 'Blacklisted')], max_length=255)),
                ('va_type', models.CharField(choices=[('Prospect', 'Prospect'), ('Customer Direct', 'Customer Direct'), ('Customer Channel', 'Customer Channel'), ('Channel Partner / Reseeller', 'Channel Partner / Reseeller'), ('Installation Partner', 'Installation Partner'), ('Technology Partner', 'Technology Partner'), ('Other', 'Other')], max_length=255)),
                ('va_partner_type', models.CharField(choices=[('Contractor', 'Contractor'), ('Service Provider', 'Service Provider'), ('Customer Channel', 'Customer Channel'), ('Indirect', 'Indirect'), ('Payroll Engineer', 'Payroll Engineer')], max_length=255)),
                ('va_expense_type', models.CharField(choices=[('Direct', 'Direct'), ('Indriect', 'Indriect'), ('Both', 'Both')], max_length=255)),
                ('va_industry', models.CharField(blank=True, choices=[('IT', 'IT'), ('Agriculture', 'Agriculture'), ('Apparel', 'Apparel'), ('Banking', 'Banking'), ('Chemicals', 'Chemicals'), ('Construction', 'Construction'), ('Consulting', 'Consulting'), ('Education', 'Education'), ('Electronics', 'Electronics'), ('Energy', 'Energy'), ('Engineering', 'Engineering'), ('Finance', 'Finance'), ('Government', 'Government'), ('Healthcare', 'Healthcare'), ('Insurance', 'Insurance'), ('Machinery', 'Machinery'), ('Media', 'Media'), ('Recreation', 'Recreation'), ('Retail', 'Retail'), ('Shipping', 'Shipping'), ('Technology', 'Technology'), ('Biotechnology', 'Biotechnology'), ('Communications', 'Communications'), ('Entertainment', 'Entertainment'), ('Environmental', 'Environmental'), ('Food & Beverage', 'Food & Beverage'), ('Manufacturing', 'Manufacturing'), ('Not For Profit', 'Not For Profit'), ('Telecommunications', 'Telecommunications'), ('Transportation', 'Transportation'), ('Utilities', 'Utilities'), ('Other', 'Other')], max_length=255)),
                ('va_bank_account_no', models.CharField(blank=True, max_length=255)),
                ('va_bank_branch', models.CharField(blank=True, max_length=255)),
                ('va_holder_name', models.CharField(blank=True, max_length=255)),
                ('va_bank_code', models.CharField(blank=True, max_length=255)),
                ('va_bank_address', models.CharField(blank=True, max_length=255)),
                ('va_bank_account_country_code', models.CharField(blank=True, choices=[('AF', 'AF'), ('AL', 'AL'), ('DZ', 'DZ'), ('AS', 'AS'), ('AD', 'AD'), ('AO', 'AO'), ('AI', 'AI'), ('AQ', 'AQ'), ('AG', 'AG'), ('AR', 'AR'), ('AM', 'AM'), ('AW', 'AW'), ('AU', 'AU'), ('AT', 'AT'), ('AZ', 'AZ'), ('BS', 'BS'), ('BH', 'BH'), ('BD', 'BD'), ('BB', 'BB'), ('BY', 'BY'), ('BE', 'BE'), ('BZ', 'BZ'), ('BJ', 'BJ'), ('BM', 'BM'), ('BT', 'BT'), ('BO', 'BO'), ('BA', 'BA'), ('BW', 'BW'), ('BV', 'BV'), ('BR', 'BR'), ('IO', 'IO'), ('BN', 'BN'), ('BG', 'BG'), ('BF', 'BF'), ('BI', 'BI'), ('KH', 'KH'), ('CM', 'CM'), ('CA', 'CA'), ('CV', 'CV'), ('KY', 'KY'), ('CF', 'CF'), ('TD', 'TD'), ('CL', 'CL'), ('CN', 'CN'), ('CX', 'CX'), ('CC', 'CC'), ('CO', 'CO'), ('KM', 'KM'), ('CG', 'CG'), ('CD', 'CD'), ('CK', 'CK'), ('CR', 'CR'), ('CI', 'CI'), ('HR', 'HR'), ('CU', 'CU'), ('CY', 'CY'), ('CZ', 'CZ'), ('DK', 'DK'), ('DJ', 'DJ'), ('DM', 'DM'), ('DO', 'DO'), ('TP', 'TP'), ('EC', 'EC'), ('EG', 'EG'), ('SV', 'SV'), ('GQ', 'GQ'), ('ER', 'ER'), ('EE', 'EE'), ('ET', 'ET'), ('XA', 'XA'), ('FK', 'FK'), ('FO', 'FO'), ('FJ', 'FJ'), ('FI', 'FI'), ('FR', 'FR'), ('GF', 'GF'), ('PF', 'PF'), ('TF', 'TF'), ('GA', 'GA'), ('GM', 'GM'), ('GE', 'GE'), ('DE', 'DE'), ('GH', 'GH'), ('GI', 'GI'), ('GR', 'GR'), ('GL', 'GL'), ('GD', 'GD'), ('GP', 'GP'), ('GU', 'GU'), ('GT', 'GT'), ('XU', 'XU'), ('GN', 'GN'), ('GW', 'GW'), ('GY', 'GY'), ('HT', 'HT'), ('HM', 'HM'), ('HN', 'HN'), ('HK', 'HK'), ('HU', 'HU'), ('IS', 'IS'), ('IN', 'IN'), ('ID', 'ID'), ('IR', 'IR'), ('IQ', 'IQ'), ('IE', 'IE'), ('IL', 'IL'), ('IT', 'IT'), ('JM', 'JM'), ('JP', 'JP'), ('XJ', 'XJ'), ('JO', 'JO'), ('KZ', 'KZ'), ('KE', 'KE'), ('KI', 'KI'), ('KP', 'KP'), ('KR', 'KR'), ('KW', 'KW'), ('KG', 'KG'), ('LA', 'LA'), ('LV', 'LV'), ('LB', 'LB'), ('LS', 'LS'), ('LR', 'LR'), ('LY', 'LY'), ('LI', 'LI'), ('LT', 'LT'), ('LU', 'LU'), ('MO', 'MO'), ('MK', 'MK'), ('MG', 'MG'), ('MW', 'MW'), ('MY', 'MY'), ('MV', 'MV'), ('ML', 'ML'), ('MT', 'MT'), ('XM', 'XM'), ('MH', 'MH'), ('MQ', 'MQ'), ('MR', 'MR'), ('MU', 'MU'), ('YT', 'YT'), ('MX', 'MX'), ('FM', 'FM'), ('MD', 'MD'), ('MC', 'MC'), ('MN', 'MN'), ('MS', 'MS'), ('MA', 'MA'), ('MZ', 'MZ'), ('MM', 'MM'), ('NA', 'NA'), ('NR', 'NR'), ('NP', 'NP'), ('AN', 'AN'), ('NL', 'NL'), ('NC', 'NC'), ('NZ', 'NZ'), ('NI', 'NI'), ('NE', 'NE'), ('NG', 'NG'), ('NU', 'NU'), ('NF', 'NF'), ('MP', 'MP'), ('NO', 'NO'), ('OM', 'OM'), ('PK', 'PK'), ('PW', 'PW'), ('PS', 'PS'), ('PA', 'PA'), ('PG', 'PG'), ('PY', 'PY'), ('PE', 'PE'), ('PH', 'PH'), ('PN', 'PN'), ('PL', 'PL'), ('PT', 'PT'), ('PR', 'PR'), ('QA', 'QA'), ('RE', 'RE'), ('RO', 'RO'), ('RU', 'RU'), ('RW', 'RW'), ('SH', 'SH'), ('KN', 'KN'), ('LC', 'LC'), ('PM', 'PM'), ('VC', 'VC'), ('WS', 'WS'), ('SM', 'SM'), ('ST', 'ST'), ('SA', 'SA'), ('SN', 'SN'), ('RS', 'RS'), ('SC', 'SC'), ('SL', 'SL'), ('SG', 'SG'), ('SK', 'SK'), ('SI', 'SI'), ('XG', 'XG'), ('SB', 'SB'), ('SO', 'SO'), ('ZA', 'ZA'), ('GS', 'GS'), ('SS', 'SS'), ('ES', 'ES'), ('LK', 'LK'), ('SD', 'SD'), ('SR', 'SR'), ('SJ', 'SJ'), ('SZ', 'SZ'), ('SE', 'SE'), ('CH', 'CH'), ('SY', 'SY'), ('TW', 'TW'), ('TJ', 'TJ'), ('TZ', 'TZ'), ('TH', 'TH'), ('TG', 'TG'), ('TK', 'TK'), ('TO', 'TO'), ('TT', 'TT'), ('TN', 'TN'), ('TR', 'TR'), ('TM', 'TM'), ('TC', 'TC'), ('TV', 'TV'), ('UG', 'UG'), ('UA', 'UA'), ('AE', 'AE'), ('GB', 'GB'), ('US', 'US'), ('UM', 'UM'), ('UY', 'UY'), ('UZ', 'UZ'), ('VU', 'VU'), ('VA', 'VA'), ('VE', 'VE'), ('VN', 'VN'), ('VG', 'VG'), ('VI', 'VI'), ('WF', 'WF'), ('EH', 'EH'), ('YE', 'YE'), ('YU', 'YU'), ('ZM', 'ZM'), ('ZW', 'ZW')], max_length=255)),
                ('va_ifsc_code', models.CharField(blank=True, max_length=255)),
                ('va_bank_zip', models.CharField(blank=True, max_length=255)),
                ('va_swift_code', models.CharField(blank=True, max_length=255)),
                ('va_bank_id', models.CharField(blank=True, max_length=255)),
                ('va_sort_code', models.CharField(blank=True, max_length=255)),
                ('va_bank_state', models.CharField(blank=True, max_length=255)),
                ('va_bsb_code', models.CharField(blank=True, max_length=255)),
                ('va_benen_bank_acc_type', models.CharField(blank=True, max_length=255)),
                ('va_transit_no', models.CharField(blank=True, max_length=255)),
                ('va_tax', models.CharField(blank=True, max_length=255)),
                ('va_routing_no', models.CharField(blank=True, max_length=255)),
                ('va_international_bank_account_no', models.CharField(blank=True, max_length=255)),
                ('va_company_name', models.CharField(blank=True, max_length=255)),
                ('va_company_headquater', models.CharField(blank=True, max_length=255)),
                ('va_nunmber_of_direct_employee', models.CharField(blank=True, max_length=255)),
                ('va_company_registration_no', models.CharField(blank=True, max_length=255)),
                ('va_gst_registration_no', models.CharField(blank=True, max_length=255)),
                ('va_statutory_details', models.CharField(blank=True, max_length=255)),
                ('va_service_registration_no', models.CharField(blank=True, max_length=255)),
                ('va_tax_identifcation_no', models.CharField(blank=True, max_length=255)),
                ('va_bank_accept_usd', models.CharField(blank=True, max_length=255)),
                ('va_bank_accept_euro', models.CharField(blank=True, max_length=255)),
                ('va_company_24x7_support', models.CharField(blank=True, max_length=255)),
                ('va_no_call_support_permonth', models.CharField(blank=True, max_length=255)),
                ('va_communication_method', models.CharField(blank=True, max_length=255)),
                ('va_multilingual_helpdesk', models.CharField(blank=True, max_length=255)),
                ('va_company_web_access', models.CharField(blank=True, max_length=255)),
                ('va_english_speaking_engineers', models.CharField(blank=True, max_length=255)),
                ('va_english_speaking_engineers_tig', models.CharField(blank=True, max_length=255)),
                ('va_call_logging_process', models.CharField(blank=True, max_length=255)),
                ('va_billing_address', models.CharField(blank=True, max_length=255)),
                ('va_shipping_address', models.CharField(blank=True, max_length=255)),
                ('va_billing_street', models.TextField(blank=True, max_length=1024)),
                ('va_shipping_street', models.TextField(blank=True, max_length=1024)),
                ('va_billing_city', models.CharField(blank=True, max_length=255)),
                ('va_shipping_city', models.CharField(blank=True, max_length=255)),
                ('va_billing_zip', models.CharField(blank=True, max_length=255)),
                ('va_shipping_zip', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('va_billing_country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='va_billing_country', to='cities_light.country')),
                ('va_billing_state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='va_billing_state', to='cities_light.region')),
                ('va_shipping_country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='va_shipping_country', to='cities_light.country')),
                ('va_shipping_state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='va_shipping_state', to='cities_light.region')),
            ],
        ),
    ]
