# Generated by Django 4.2 on 2024-07-08 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_vendoraccount_va_billing_country_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendoraccount',
            old_name='va_phone_number',
            new_name='va_primary_contact_number',
        ),
    ]
