# Generated by Django 4.2 on 2024-07-08 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rename_ca_record_type_customeraccount_record_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendoraccount',
            old_name='va_phone_no',
            new_name='va_phone_number',
        ),
    ]
