# Generated by Django 4.2 on 2024-07-11 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
        ('accounts', '0009_rename_va_parent_acc_vendoraccount_va_parent_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraccount',
            name='ca_billing_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_customer_accounts', to='cities_light.country'),
        ),
        migrations.AlterField(
            model_name='customeraccount',
            name='ca_billing_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_customer_accounts', to='cities_light.region'),
        ),
        migrations.AlterField(
            model_name='customeraccount',
            name='ca_payment_terms',
            field=models.CharField(choices=[('NET0', 'NET0'), ('NET10', 'NET10'), ('NET30', 'NET30'), ('NET45', 'NET45'), ('NET60', 'NET60'), ('NET90', 'NET90')], max_length=64),
        ),
        migrations.AlterField(
            model_name='customeraccount',
            name='ca_shipping_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_customer_accounts', to='cities_light.country'),
        ),
        migrations.AlterField(
            model_name='customeraccount',
            name='ca_shipping_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_customer_accounts', to='cities_light.region'),
        ),
    ]
