# Generated by Django 4.2 on 2024-07-11 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_customeraccount_ca_billing_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendoraccount',
            name='va_spoc_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='vendoraccount',
            name='va_spoc_phone_number',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
