# Generated by Django 4.2 on 2024-07-11 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_vendoraccount_va_spoc_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendoraccount',
            name='va_spoc_name',
        ),
        migrations.RemoveField(
            model_name='vendoraccount',
            name='va_spoc_phone_number',
        ),
        migrations.AddField(
            model_name='customeraccount',
            name='ca_spoc_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='customeraccount',
            name='ca_spoc_phone_number',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
