# Generated by Django 4.2 on 2024-07-17 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_vendoraccount_va_spoc_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customeraccount',
            options={'permissions': [('can_add_new_customer_account', 'can add new customer account')]},
        ),
    ]
