# Generated by Django 4.2 on 2024-07-03 08:00

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('project_site', '0002_alter_projectsite_ps_zip_site_classification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectsite',
            name='ps_working_days',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thrusday', 'Thrusday'), ('Friday', 'Friday'), ('Satursay', 'Satursay')], max_length=1024),
        ),
    ]
