# Generated by Django 4.2 on 2024-07-03 08:06

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('project_site', '0003_alter_projectsite_ps_working_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectsite',
            name='ps_working_days',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=1024),
        ),
    ]
