# Generated by Django 4.2 on 2024-07-19 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
        ('project_site', '0004_alter_projectsite_ps_working_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectsite',
            name='ps_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ps_country', to='cities_light.country'),
        ),
        migrations.AlterField(
            model_name='projectsite',
            name='ps_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ps_state', to='cities_light.region'),
        ),
    ]
