# Generated by Django 4.2 on 2024-06-26 09:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_remove_customeraccount_created_by_and_more'),
        ('projects', '0008_customerproject_cp_cancelled_ticket_mutiplier_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('so_po_number', models.CharField(max_length=32)),
                ('so_po_status', models.CharField(max_length=16)),
                ('so_comment', models.TextField(blank=True, max_length=1024)),
                ('so_tig_entity', models.CharField(choices=[('Total IT Consult LLP', 'Total IT Consult LLP'), ('Total IT Consult Pty ltd', 'Total IT Consult Pty ltd'), ('Total IT Global Pte Ltd', 'Total IT Global Pte Ltd'), ('Total IT Global Sdn. Bhd.', 'Total IT Global Sdn. Bhd.'), ('Total IT Global KK,Japan', 'Total IT Global KK,Japan'), ('TIC Netherlands B.V.', 'TIC Netherlands B.V.'), ('Total IT Global Inc.', 'Total IT Global Inc.'), ('Total IT Global NZ Ltd', 'Total IT Global NZ Ltd'), ('Total IT Global HK Ltd', 'Total IT Global HK Ltd'), ('Total IT Consult DK ApS', 'Total IT Consult DK ApS'), ('Total IT Global Finalnd OY', 'Total IT Global Finalnd OY'), ('TOTAL IT GLOBAL POLAND Sp. z o .o', 'TOTAL IT GLOBAL POLAND Sp. z o .o'), ('Total IT Global France', 'Total IT Global France'), ('Total IT Global Company Limited', 'Total IT Global Company Limited'), ('Total IT Global Germany GMBH', 'Total IT Global Germany GMBH'), ('Total IT Norway AS', 'Total IT Norway AS'), ('TI Global Sweden AB', 'TI Global Sweden AB'), ('Total IT Global UK Limited', 'Total IT Global UK Limited')], max_length=64)),
                ('so_po_start_date', models.DateField()),
                ('so_po_end_date', models.DateField()),
                ('so_currency', models.CharField(choices=[('AED - UAE Dirham', 'AED - UAE Dirham'), ('AUD - Australian Dollar', 'AUD - Australian Dollar'), ('CAD - Canadian Dollar', 'CAD - Canadian Dollar'), ('CHF - Swiss Franc', 'CHF - Swiss Franc'), ('DKK - Danish Krone', 'DKK - Danish Krone'), ('EUR - Euro', 'EUR - Euro'), ('GBP - British Pound', 'GBP - British Pound'), ('HKD - Hong Kong Dollar', 'HKD - Hong Kong Dollar'), ('INR - Indian Rupee', 'INR - Indian Rupee'), ('JPY - Japanese Yen', 'JPY - Japanese Yen'), ('KRW - Korean Won', 'KRW - Korean Won'), ('MYR - Malaysian Ringgit', 'MYR - Malaysian Ringgit'), ('NOK - Norwegian Krone', 'NOK - Norwegian Krone'), ('NZD - New Zealand Dollar', 'NZD - New Zealand Dollar'), ('PLN - Polish Zloty', 'PLN - Polish Zloty'), ('SEK - Swedish Krona', 'SEK - Swedish Krona'), ('SGD - Singapore Dollar', 'SGD - Singapore Dollar'), ('THB - Thai Baht', 'THB - Thai Baht'), ('USD - U.S. Dollar', 'USD - U.S. Dollar')], max_length=32)),
                ('so_po_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('so_po_amount_utilised', models.DecimalField(decimal_places=2, max_digits=10)),
                ('so_po_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('so_tax_included', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('so_bill_to_address', models.TextField(max_length=1024)),
                ('so_ship_to_address', models.TextField(max_length=1024)),
                ('so_record_type', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('so_customer_vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='so_customer_vendor', to='accounts.customeraccount')),
                ('so_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='so_project', to='projects.customerproject')),
            ],
        ),
    ]
