# Generated by Django 4.2 on 2024-06-26 09:42

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_salesorder_so_po_amount_utilised'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='so_po_amount_utilised',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.1'), max_digits=10),
        ),
    ]
