# Generated by Django 4.2 on 2024-06-26 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_salesorder_so_po_amount_utilised'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='so_po_amount_utilised',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
