# Generated by Django 4.2 on 2024-06-27 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_salesorder_so_po_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='so_po_status',
            field=models.CharField(choices=[('Released', 'Released'), ('Draft', 'Draft')], max_length=16),
        ),
    ]
