# Generated by Django 4.2 on 2024-07-12 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_salesorder_so_po_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='so_po_amount_utilised',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='so_po_balance',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='so_ship_to_address',
            field=models.TextField(blank=True, max_length=1024),
        ),
    ]
